### ISSUE TITLE
:hover doesn't work with @variant dark

### ISSUE THREAD

**Issue by jonasbrinkhoff** [ChanceArthur/tailwindcss-dark-mode#26]
I'm trying to create a dark variant of the custom utility `.component`. The component has a default and a hover state. But in the compiled CSS, the dark mode does not have the `:hover` pseudo class anymore.

Here's the CSS:
```css
@variants dark {
  .component {
    @apply bg-green;
  }

  .component:hover {
    @apply bg-red;
  }
}
```

And here's what it compiles to:

```css
.component {
  --bg-opacity: 1;
  background-color: #29A575;
  background-color: rgba(41, 165, 117, var(--bg-opacity));
}

.component:hover {
  --bg-opacity: 1;
  background-color: #C8223D;
  background-color: rgba(200, 34, 61, var(--bg-opacity));
}

.mode-dark .dark\:component {
  --bg-opacity: 1;
  background-color: #29A575;
  background-color: rgba(41, 165, 117, var(--bg-opacity));
}

.mode-dark .dark\:component {
  --bg-opacity: 1;
  background-color: #C8223D;
  background-color: rgba(200, 34, 61, var(--bg-opacity));
}
```

Is this an issue with how Tailwind generates variants or is there a way of solving this problem (without having to define all hover states for the dark mode by hand)?
