### ISSUE TITLE
Wrongly generated css code

### ISSUE THREAD

**Issue by nenadjelovac** [ChanceArthur/tailwindcss-dark-mode#8]
Hey, great idea for this plugin! 

However, I haven't been able to get it to work. I run into an issue where the css it generates has two extra backslashes:

```css
.mode-dark .dark\\\:bg-white {
  background-color:       #fff !important;
}
```

It should have only one backslash:

```css
.mode-dark .dark\:bg-white {
  background-color:       #fff !important;
}
```

Any idea what might be the cause? I'm running postcss (and tailwind) via gulp (if that matters).
